num1=int(input("Enter the first  number: "))
num2=int(input("Enter the second number: "))

print("arithmetic operations:")
print("sum =",num1+num2)
print("product =",num1*num2)
print("quotient =",num1/num2)
print("remainder =",num1%num2)
print("exponent =",num1**num2)
print("division =",num1/num2)
print("subtraction =",num1-num2)